// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: code.proto

package code

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendCodeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mobile        string                 `protobuf:"bytes,1,opt,name=Mobile,proto3" json:"Mobile,omitempty"`
	Code          int32                  `protobuf:"varint,2,opt,name=Code,proto3" json:"Code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendCodeReq) Reset() {
	*x = SendCodeReq{}
	mi := &file_code_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendCodeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendCodeReq) ProtoMessage() {}

func (x *SendCodeReq) ProtoReflect() protoreflect.Message {
	mi := &file_code_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendCodeReq.ProtoReflect.Descriptor instead.
func (*SendCodeReq) Descriptor() ([]byte, []int) {
	return file_code_proto_rawDescGZIP(), []int{0}
}

func (x *SendCodeReq) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *SendCodeReq) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

type SendCodeRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=Success,proto3" json:"Success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendCodeRes) Reset() {
	*x = SendCodeRes{}
	mi := &file_code_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendCodeRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendCodeRes) ProtoMessage() {}

func (x *SendCodeRes) ProtoReflect() protoreflect.Message {
	mi := &file_code_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendCodeRes.ProtoReflect.Descriptor instead.
func (*SendCodeRes) Descriptor() ([]byte, []int) {
	return file_code_proto_rawDescGZIP(), []int{1}
}

func (x *SendCodeRes) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_code_proto protoreflect.FileDescriptor

const file_code_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"code.proto\"9\n" +
	"\vSendCodeReq\x12\x16\n" +
	"\x06Mobile\x18\x01 \x01(\tR\x06Mobile\x12\x12\n" +
	"\x04Code\x18\x02 \x01(\x05R\x04Code\"'\n" +
	"\vSendCodeRes\x12\x18\n" +
	"\aSuccess\x18\x01 \x01(\bR\aSuccess2.\n" +
	"\x04code\x12&\n" +
	"\bSendCode\x12\f.SendCodeReq\x1a\f.SendCodeResB\bZ\x06.;codeb\x06proto3"

var (
	file_code_proto_rawDescOnce sync.Once
	file_code_proto_rawDescData []byte
)

func file_code_proto_rawDescGZIP() []byte {
	file_code_proto_rawDescOnce.Do(func() {
		file_code_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_code_proto_rawDesc), len(file_code_proto_rawDesc)))
	})
	return file_code_proto_rawDescData
}

var file_code_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_code_proto_goTypes = []any{
	(*SendCodeReq)(nil), // 0: SendCodeReq
	(*SendCodeRes)(nil), // 1: SendCodeRes
}
var file_code_proto_depIdxs = []int32{
	0, // 0: code.SendCode:input_type -> SendCodeReq
	1, // 1: code.SendCode:output_type -> SendCodeRes
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_code_proto_init() }
func file_code_proto_init() {
	if File_code_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_code_proto_rawDesc), len(file_code_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_code_proto_goTypes,
		DependencyIndexes: file_code_proto_depIdxs,
		MessageInfos:      file_code_proto_msgTypes,
	}.Build()
	File_code_proto = out.File
	file_code_proto_goTypes = nil
	file_code_proto_depIdxs = nil
}
